# Generated by Django 4.1.7 on 2023-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submit_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('blog_type', models.CharField(choices=[('Data Science', 'Data Science'), ('Cloud Computing', 'Cloud Computing'), ('Web Technology', 'Web Technology'), ('Cyber Security', 'Cyber Security'), ('Devops', 'Devops'), ('Coding', 'Coding')], max_length=100)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
