# Generated by Django 4.1.7 on 2023-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_blog',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
